[package]
name = "trie-standardmap"
description = "Standard test map for profiling tries"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[dependencies]
keccak-hasher = { path = "../keccak-hasher" }
hash-db = { path = "../../hash-db" }