[package]
name = "trie-standardmap"
description = "Standard test map for profiling tries"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2"

[dependencies]
keccak-hasher = { path = "../keccak-hasher" }
hash-db = { path = "../../hash-db" }
criterion = "0.1.2"