[package]
description = "Parity Common crates"
name = "parity-common"
version = "0.1"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[workspace]
members = [
	"ethcore-bytes",
	"kvdb",
]