[workspace]
members = [
	"hashdb",
	"keccak-hash",
	"kvdb",
	"kvdb-rocksdb",
	"memorydb",
	"parity-bytes",
	"parity-crypto",
	"path",
	"patricia_trie",
	"plain_hasher",
	"rlp",
	"trie-standardmap",
	"triehash",
]