[workspace]
members = [
	"fixed-hash",
	"hashdb",
	"hex-prefix-encoding",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"memorydb",
	"parity-bytes",
	"parity-crypto",
	"parity-path",
	"patricia_trie",
	"plain_hasher",
	"rlp",
	"transaction-pool",
	"trace-time",
	"triehash",
	"trie-standardmap",
	"triestream",
	"uint"
]
