[package]
name = "trie-db"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2.0"

[dependencies]
log = { version = "0.3" }
rand = { version = "0.4" }
elastic-array = { version = "0.10" }
hash-db = { path = "../hash-db" , version = "0.9.0"}

[dev-dependencies]
env_logger = "0.5"
memory-db = { path = "../memory-db", version = "0.9.0" }
trie-root = { path = "../trie-root", version = "0.9.0"}
trie-standardmap = { path = "../test-support/trie-standardmap", version = "0.9.0" }
keccak-hasher = { path = "../test-support/keccak-hasher", version = "0.2.0" }
# DISABLE the following line when publishing until cyclic dependencies are resolved https://github.com/rust-lang/cargo/issues/4242
reference-trie = { path = "../test-support/reference-trie", version = "0.1.0" }
hex-literal = "0.1"
criterion = "0.1.2"

[[bench]]
name = "bench"
harness = false
