[package]
name = "trie-db"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2"

[dependencies]
elastic-array = "0.10"
log = "0.3"
rand = "0.4"
hash-db = { version = "0.3", path = "../hash-db" }

[dev-dependencies]
env_logger = "0.5"
memory-db = { path = "../memory-db", default-features = false }
trie-root = { path = "../trie-root", default-features = false }
trie-standardmap = { path = "../test-support/trie-standardmap", default-features = false }
keccak-hasher = { path = "../test-support/keccak-hasher" }
reference-trie = { path = "../test-support/reference-trie" }