[package]
name = "trie-db"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
repository = "https://github.com/paritytech/parity-common"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
log = "0.3"
rand = "0.4"
hashdb = { version = "0.3", path = "../hashdb" }

[dev-dependencies]
env_logger = "0.5"
parity-codec = { version = "~2.0.1" }
parity-codec-derive = { version = "~2.0.1" }
memorydb = { path = "../memorydb", default-features = false }
trie-root = { path = "../trie-root", default-features = false }
trie-standardmap = { path = "../test-support/trie-standardmap", default-features = false }
keccak-hasher = { path = "../test-support/keccak-hasher" }
hex-prefix-encoding = { path = "../hex-prefix-encoding" }
reference-trie = { path = "../test-support/reference-trie" }