[package]
name = "keccak-hasher"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Keccak-256 implementation of the Hasher trait"
repository = "https://github.com/paritytech/parity/"
license = "Apache-2"

[dependencies]
tiny-keccak = "1.4.2"
hash-db = { path = "../../hash-db" }
hash256-std-hasher = { path = "../../hash256-std-hasher" }
