[package]
name = "memory-db"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory implementation of hash-db, useful for tests"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2.0"

[dependencies]
heapsize = { version = "0.4", optional = true}
hash-db = { path = "../hash-db", default-features = false, version = "0.11.0"}
hashmap_core = { version = "0.1" }

[dev-dependencies]
keccak-hasher = { path = "../test-support/keccak-hasher", version = "0.11.0"}
criterion = "0.2.8"

[features]
default = ["std"]
std = [
  "heapsize",
  "hash-db/std",
  "hashmap_core/disable",
]

[[bench]]
name = "bench"
harness = false
