[package]
name = "memory-db"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in-memory implementation of hashdb"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2"

[dependencies]
heapsize = "0.4"
hash-db = { path = "../hash-db" }

[dev-dependencies]
keccak-hasher = { path = "../test-support/keccak-hasher" }
tiny-keccak = "1.4.2"