[package]
name = "memory-db"
version = "0.9.2"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory implementation of hash-db, useful for tests"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2.0"

[dependencies]
heapsize = "0.4"
hash-db = { path = "../hash-db", default-features = false, version = "0.9.0"}
hashbrown = "0.1"

[dev-dependencies]
keccak-hasher = { path = "../test-support/keccak-hasher", default-features = false, version = "0.2.1"}
criterion = "0.2.8"

[features]
default = ["std"]
std = [
  "hash-db/std",
]

[[bench]]
name = "bench"
harness = false
