[package]
name = "memory-db"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory implementation of hash-db, useful for tests"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2"

[[bench]]
name = "bench"
harness = false

[dependencies]
heapsize = "0.4"
hash-db = { path = "../hash-db" }

[dev-dependencies]
keccak-hasher = { path = "../test-support/keccak-hasher" }
criterion = "0.1.2"