[package]
name = "trie-standardmap"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
description = "Standard test map for profiling tries"

[dependencies]
ethereum-types = "0.3"
keccak-hash = { version = "0.1", path = "../keccak-hash" }
parity-bytes = { path = "../parity-bytes" }
rlp = { path = "../rlp" }
