[package]
name = "hash-db"
version = "0.9.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trait for hash-keyed databases."
license = "Apache-2.0"
categories = [ "no-std" ]

[dependencies]
hashbrown = { version = "0.1" }

[features]
default = ["std"]
std = [
]
