[package]
name = "hash-db"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "trait for hash-keyed databases."
license = "Apache-2"

[dependencies]

[features]
default = ["std"]
std = []
