[package]
name = "reference-trie"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Simple reference trie format"
repository = "https://github.com/paritytech/trie/"
license = "Apache-2"

[dependencies]
hash-db = { path = "../../hash-db" }
hash256-std-hasher = { path = "../../hash256-std-hasher" }
keccak-hasher = { path = "../keccak-hasher" }
trie-db = { path = "../../trie-db", default-features = false }
trie-root = { path = "../../trie-root", default-features = false }
parity-codec = { version = "2.1" }
parity-codec-derive = { version = "2.1" }

[dev-dependencies]
trie-bench = { path = "../trie-bench" }
criterion = "0.1.2"

[[bench]]
name = "bench"
harness = false

[features]
default = ["std"]
# no actual support for std, only to avoid a cargo issues
std = [
  "trie-db/std",
]
