[package]
name = "reference-trie"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Simple reference trie format"
repository = "https://github.com/paritytech/trie/"
license = "Apache-2"

[dependencies]
hash-db = { path = "../../hash-db" }
hash256-std-hasher = { path = "../../hash256-std-hasher" }
keccak-hasher = { path = "../keccak-hasher" }
trie-db = { path = "../../trie-db" }
trie-root = { path = "../../trie-root" }
parity-codec = { version = "2.1" }
parity-codec-derive = { version = "2.1" }

[dev-dependencies]
trie-bench = { path = "../trie-bench" }
criterion = "0.1.2"

[[bench]]
name = "bench"
harness = false
