[package]
name = "reference-trie"
version = "0.12.3"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Simple reference trie format"
repository = "https://github.com/paritytech/trie/"
license = "Apache-2.0"

[dependencies]
hash-db = { path = "../../hash-db" , version = "0.12.3"}
hash256-std-hasher = { path = "../../hash256-std-hasher", version = "0.12.3" }
keccak-hasher = { path = "../keccak-hasher", version = "0.12.3" }
trie-db = { path = "../../trie-db", default-features = false, version = "0.12.3"}
trie-root = { path = "../../trie-root", default-features = false, version = "0.12.3" }
parity-codec = "3.0"
parity-codec-derive = "3.0"

[dev-dependencies]
trie-bench = { path = "../trie-bench", version = "0.12.3" }
criterion = "0.2.8"

[[bench]]
name = "bench"
harness = false

[features]
default = ["std"]
# no actual support for std, only to avoid a cargo issues
std = [
  "trie-db/std",
  "trie-root/std",
]
