[package]
name = "triehash"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in memory patricia trie operations"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
ethereum-types = "0.3"
hashdb = { path = "../hashdb" }
keccak-hash = { path = "../keccak-hash" }
rlp = { path = "../rlp" }

[dev-dependencies]
trie-standardmap = { path = "../trie-standardmap" }
keccak-hasher = { path = "../test-support/keccak-hasher" }